apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejsui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vuejsui
  template:
    metadata:
      labels:
        app: vuejsui
    spec:
      containers:
      - name: flaskapp
        image: ghcr.io/ingos11/vuejsui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vuejsui
spec:
  selector:
    app: vuejsui
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
